name: Docker Images CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}
  UI_IMAGE_NAME: pantryprofiler-ui

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract API metadata (tags, labels) for Docker
      id: meta-api
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}

    - name: Extract UI metadata (tags, labels) for Docker
      id: meta-ui
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.UI_IMAGE_NAME }}
        
    - name: Build and push the Docker image for the API
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        
    # - name: Build and push the Docker image for the UI
    #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
    #   with:
    #     context: ./frontend
    #     push: true
    #     tags: ${{ steps.meta-ui.outputs.tags }}
    #     labels: ${{ steps.meta-ui.outputs.labels }}
